account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('image/', views.image_view, name='image'),
    path('login/', views.login_view, name='login'),
    path('accounts/login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.account_view, name='account'),
]

custom_registeration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('account.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from account.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'gender', 'phone_no', 'prof_img', 'password1', 'password2', )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class ImageForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('prof_img',)

    def clean_prof_img(self):
        prof_img = self.cleaned_data['prof_img']
        return prof_img



class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username', 'gender', 'phone_no', 'prof_img')

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        username = self.cleaned_data['username']
        return username

    def clean_gender(self):
        gender = self.cleaned_data['gender']
        return gender

    def clean_phone_no(self):
        phone_no = self.cleaned_data['phone_no']
        return phone_no

    def clean_prof_img(self):
        prof_img = self.cleaned_data['prof_img']
        return prof_img

templates/registeration/password_change.html
<form method="POST">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" placeholder="Old password" type="password" id="id_old_password" required="true">
    <input name="new_password1" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button type="submit">Update</button>&nbsp&nbsp&nbsp&nbsp<a href="{% url 'account:account' %}">Go Back</a>
</form>

templates/registeration/password_change_done.html
<p align="center">Your password has been Updated.</p>
<p>Return to <a href="{% url 'home' %}">Home.</a></p>

templates/registeration/password_reset_complete.html
<p>Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>

templates/registeration/password_reset_done.html
<p> We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.</p>
<p>If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.</p>
<p><a href="{% url 'home' %}">Return to home page</a></p>

templates/registeration/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The MyKashmir Team
{% endautoescape %}

templates/registeration/password_reset_form.html
<form method="POST">{% csrf_token %}
	<h1>Reset password</h1>
    <input name="email" placeholder="Email address" type="email" id="id_email" required="true">
	<button type="submit">Send reset email</button>  
</form>