account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('image/', views.image_view, name='image'),
    path('login/', views.login_view, name='login'),
    path('accounts/login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.account_view, name='account'),
]

custom_registeration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('account.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'main/home.html')

main/templates/main/home.html
{% load static %}

    {% if request.user.prof_img %}
      <img src="{{ request.user.prof_img.url }}" height="50px" width="50px"><br><br>
    {% else %}
      <img src="{% static 'main/images/user_default.png' %}" height="50px" width="50px"><br><br>
    {% endif %}

    {% if request.user.is_authenticated %}
      <div>Hi, {{ request.user.username }}</div>
      <div><a href="{% url 'account:account' %}">Account Settings</a></div>
      <div><a href="{% url 'account:logout' %}">Logout</a></div>
    {% else %}
      <div id="greeting-text">Hey there!</div>
      <div><a href="{% url 'account:login' %}">Sign in / Sign up</a></div>
    {% endif %}